"""Initial city and visit tables for chi check-ins

Revision ID: 4dea5fb0acc8
Revises: 
Create Date: 2026-05-07 15:32:56.075832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dea5fb0acc8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('city_en', sa.String(length=256), nullable=False),
    sa.Column('country_en', sa.String(length=256), nullable=False),
    sa.Column('city_zh', sa.String(length=256), nullable=True),
    sa.Column('country_zh', sa.String(length=256), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_city_slug'), ['slug'], unique=True)

    op.create_table('visit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('visit_date', sa.Date(), nullable=True),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('smugmug_image_key', sa.String(length=256), nullable=True),
    sa.Column('runner_name_en', sa.Text(), nullable=True),
    sa.Column('runner_name_zh', sa.Text(), nullable=True),
    sa.Column('place_note_en', sa.Text(), nullable=True),
    sa.Column('place_note_zh', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city_id', 'filename', name='uq_visit_city_filename')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visit')
    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_city_slug'))

    op.drop_table('city')
    # ### end Alembic commands ###
